#!/bin/bash
# *** Don't touch this file, instead use .config or environment variables ***

# Working directory
readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# The directory to store the built aci files
S1B_OUT_DIR="${S1B_OUT_DIR:-${DIR}/aci-files}"

# The kernel version to build and include
S1B_KERNEL_VERSION="${S1B_KERNEL_VERSION:-"4.9.6"}"

# The upstream stage1 kvm to set as dependency
S1B_UPSTREAM_STAGE1_KVM_VERSION="${S1B_UPSTREAM_STAGE1_KVM_VERSION:-"1.26.0"}"

# The kernel version suffix, e.g. ("-custom-v1")
S1B_KERNEL_VERSION_SUFFIX="${S1B_KERNEL_VERSION_SUFFIX:-"-kinvolk-v1"}"

# The value passed to `make -jX ...`
S1B_JOBS="${S1B_JOBS:-$(nproc --all)}"

# The directory to store and build the kernel in
S1B_BUILD_DIR="${S1B_BUILD_DIR:-${DIR}/build/${S1B_KERNEL_VERSION}}"

# The directory to store the aci contents (manifest, rootfs) in
S1B_ACI_DIR="${S1B_ACI_DIR:-${DIR}/aci/${S1B_KERNEL_VERSION}}"

# Optional extra kernel patches to apply
S1B_EXTRA_KERNEL_PATCH_FILES="${S1B_EXTRA_KERNEL_PATCH_FILES:-}"
S1B_EXTRA_KERNEL_PATCH_URLS="${S1B_EXTRA_KERNEL_PATCH_URLS:-}"
